(() => {
  let message='',voices=[],spoken=[],cancelled=0,changed;
  globalThis.SpeechSynthesisUtterance=class {constructor(text){this.text=text;}};
  globalThis.speechSynthesis={getVoices:()=>voices,addEventListener:(event,callback)=>{changed=callback;},cancel:()=>{cancelled++;},speak:utterance=>spoken.push(utterance)};
  const audio=new WordSpeech(text=>{message=text;});
  assert(message.includes('No Mandarin'),'Missing voice explanation');
  voices=[{lang:'en-US'},{lang:'zh-HK'},{lang:'yue-CN'}];changed();audio.speak('床');
  assert(spoken.length===0,'Must not use English or Cantonese');
  voices.push({lang:'zh-TW'},{lang:'zh-CN'});changed();
  assert(message==='' && audio.voice.lang==='zh-CN','Delayed Mandarin selection');
  audio.speak('床');assert(spoken[0].text==='床' && spoken[0].lang==='zh-CN','Speak Chinese word');
  const first=spoken[0];audio.speak('白色');
  first.onerror({error:'synthesis-failed'});assert(message==='','Ignore stale errors');
  assert(cancelled>=3 && spoken.length===2,'Cancel before replay');
  audio.setEnabled(false);audio.speak('百分之');assert(spoken.length===2 && audio.utterance===null,'Mute cancels and prevents speech');
  audio.setEnabled(true);audio.speak('白色');spoken[2].onerror({error:'not-allowed'});
  assert(message.includes('Replay'),'Playback failure is actionable');
  audio.speak('白色');audio.stop();spoken[3].onerror({error:'interrupted'});assert(message==='','Cancellation is not an error');
  let start=spoken.length;
  audio.speakList(['白色','百分之']);
  assert(spoken.length===start+1 && spoken[start].text==='白色','Start source list with first word');
  spoken[start].onend();assert(spoken[start+1].text==='百分之','Play next source word after completion');
  spoken[start+1].onend();assert(audio.utterance===null,'Finish source list');
  start=spoken.length;audio.speakList(['爸爸','白色']);audio.stop();spoken[start].onend();
  assert(spoken.length===start+1,'Navigation cancels remaining source words');
  start=spoken.length;audio.speakList(['爸爸','白色']);audio.speak('床');spoken[start].onend();
  assert(spoken.length===start+2 && spoken[start+1].text==='床','New click replaces source list');
  delete globalThis.speechSynthesis;
  const unavailable=new WordSpeech(text=>{message=text;});unavailable.speak('床');
  assert(!unavailable.supported && message.includes('not supported'),'Unsupported browser fallback');
  return 'Speech checks passed';
})();
